/* AUTO-GENERATED by scrape.mjs on 2026-08-17 — do not hand-edit. */
window.CHOPPERS_DATA = {
  "competition": {
    "club": "Conwy Golf Club",
    "name": "Conwy Choppers",
    "subtitle": "Order of Merit",
    "format": "Best 6 Stableford",
    "startDate": "2026-05-30",
    "endDate": "2026-09-30",
    "lastUpdated": "2026-08-17",
    "bestN": 6,
    "recap": "<b>Tom</b> leads on 207.",
    "moverId": null,
    "celebrate": false
  },
  "players": [
    {
      "id": "tom",
      "name": "Tom Williams",
      "short": "Tom",
      "handicap": "+0.1",
      "handicapTrend": 0.8,
      "handicapHistory": [
        -0.9,
        -0.9,
        -0.9,
        -0.3,
        -0.1,
        -0.1
      ],
      "movement": 0,
      "rounds": [
        {
          "date": "2026-08-02",
          "course": "Conwy(Caernarvonshire)",
          "points": 35,
          "gross": 74,
          "net": 73,
          "chcp": 1
        },
        {
          "date": "2026-07-22",
          "course": "Conwy(Caernarvonshire)",
          "points": 35,
          "gross": 74,
          "net": 73,
          "chcp": 1
        },
        {
          "date": "2026-06-21",
          "course": "Conwy(Caernarvonshire)",
          "points": 35,
          "gross": 74,
          "net": 73,
          "chcp": 1
        },
        {
          "date": "2026-08-14",
          "course": "Royal Birkdale",
          "points": 34,
          "gross": 74,
          "net": 74,
          "chcp": 0
        },
        {
          "date": "2026-08-11",
          "course": "Hesketh",
          "points": 34,
          "gross": 73,
          "net": 74,
          "chcp": -1
        },
        {
          "date": "2026-07-29",
          "course": "Conwy(Caernarvonshire)",
          "points": 34,
          "gross": 75,
          "net": 74,
          "chcp": 1
        },
        {
          "date": "2026-07-09",
          "course": "Wallasey",
          "points": 34,
          "gross": 73,
          "net": 74,
          "chcp": -1
        },
        {
          "date": "2026-07-01",
          "course": "Bromborough",
          "points": 34,
          "gross": 73,
          "net": 74,
          "chcp": -1
        },
        {
          "date": "2026-05-30",
          "course": "Conwy(Caernarvonshire)",
          "points": 33,
          "gross": 76,
          "net": 75,
          "chcp": 1
        },
        {
          "date": "2026-08-13",
          "course": "Hillside",
          "points": 32,
          "gross": 76,
          "net": 76,
          "chcp": 0
        },
        {
          "date": "2026-08-12",
          "course": "West Lancashire",
          "points": 32,
          "gross": 74,
          "net": 75,
          "chcp": -1
        },
        {
          "date": "2026-07-11",
          "course": "Conwy(Caernarvonshire)",
          "points": 32,
          "gross": 77,
          "net": 76,
          "chcp": 1
        },
        {
          "date": "2026-06-20",
          "course": "Conwy(Caernarvonshire)",
          "points": 32,
          "gross": 77,
          "net": 76,
          "chcp": 1
        },
        {
          "date": "2026-07-19",
          "course": "St Melyd",
          "points": 31,
          "gross": 72,
          "net": 74,
          "chcp": -2
        },
        {
          "date": "2026-08-08",
          "course": "Conwy(Caernarvonshire)",
          "points": 30,
          "gross": 79,
          "net": 78,
          "chcp": 1
        },
        {
          "date": "2026-07-08",
          "course": "Conwy(Caernarvonshire)",
          "points": 28,
          "gross": 78,
          "net": 80,
          "chcp": -2
        },
        {
          "date": "2026-08-10",
          "course": "Southport & Ainsdale",
          "points": 27,
          "gross": 80,
          "net": 81,
          "chcp": -1
        }
      ]
    },
    {
      "id": "josh",
      "name": "Josh Morris",
      "short": "Josh",
      "handicap": "3.8",
      "handicapTrend": 0.8,
      "handicapHistory": [
        2.8,
        3,
        3.2,
        3.4,
        3.2,
        4.3,
        4.4,
        3.8
      ],
      "movement": 0,
      "rounds": [
        {
          "date": "2026-08-14",
          "course": "Formby Ladies",
          "points": 36,
          "gross": 70,
          "net": 71,
          "chcp": -1
        },
        {
          "date": "2026-07-09",
          "course": "Wallasey",
          "points": 36,
          "gross": 76,
          "net": 72,
          "chcp": 4
        },
        {
          "date": "2026-08-11",
          "course": "Hesketh",
          "points": 35,
          "gross": 77,
          "net": 73,
          "chcp": 4
        },
        {
          "date": "2026-07-14",
          "course": "Abergele",
          "points": 33,
          "gross": 78,
          "net": 75,
          "chcp": 3
        },
        {
          "date": "2026-08-12",
          "course": "West Lancashire",
          "points": 31,
          "gross": 80,
          "net": 76,
          "chcp": 4
        },
        {
          "date": "2026-08-10",
          "course": "Southport & Ainsdale",
          "points": 31,
          "gross": 81,
          "net": 77,
          "chcp": 4
        },
        {
          "date": "2026-08-02",
          "course": "Conwy(Caernarvonshire)",
          "points": 30,
          "gross": 84,
          "net": 78,
          "chcp": 6
        },
        {
          "date": "2026-05-30",
          "course": "Conwy(Caernarvonshire)",
          "points": 30,
          "gross": 84,
          "net": 78,
          "chcp": 6
        },
        {
          "date": "2026-07-22",
          "course": "Conwy(Caernarvonshire)",
          "points": 28,
          "gross": 86,
          "net": 80,
          "chcp": 6
        },
        {
          "date": "2026-07-19",
          "course": "St Melyd",
          "points": 28,
          "gross": 79,
          "net": 77,
          "chcp": 2
        },
        {
          "date": "2026-07-04",
          "course": "Conwy(Caernarvonshire)",
          "points": 27,
          "gross": 84,
          "net": 81,
          "chcp": 3
        },
        {
          "date": "2026-08-13",
          "course": "Hillside",
          "points": 26,
          "gross": 88,
          "net": 82,
          "chcp": 6
        },
        {
          "date": "2026-06-20",
          "course": "Conwy(Caernarvonshire)",
          "points": 26,
          "gross": 88,
          "net": 82,
          "chcp": 6
        }
      ]
    },
    {
      "id": "callum",
      "name": "Callum Bennett",
      "short": "Callum",
      "handicap": "21.1",
      "handicapTrend": -0.2,
      "handicapHistory": [
        21.3,
        21.3,
        21.3,
        21.3,
        21.3,
        21.3,
        21.3,
        21.1
      ],
      "movement": 0,
      "rounds": [
        {
          "date": "2026-06-05",
          "course": "Conwy(Caernarvonshire)",
          "points": 36,
          "gross": 101,
          "net": 72,
          "chcp": 29
        },
        {
          "date": "2026-08-14",
          "course": "Conwy(Caernarvonshire)",
          "points": 35,
          "gross": 102,
          "net": 73,
          "chcp": 29
        },
        {
          "date": "2026-07-22",
          "course": "Conwy(Caernarvonshire)",
          "points": 34,
          "gross": 103,
          "net": 74,
          "chcp": 29
        },
        {
          "date": "2026-07-19",
          "course": "St Melyd",
          "points": 33,
          "gross": 94,
          "net": 72,
          "chcp": 22
        },
        {
          "date": "2026-08-06",
          "course": "Conwy(Caernarvonshire)",
          "points": 28,
          "gross": 103,
          "net": 80,
          "chcp": 23
        },
        {
          "date": "2026-07-17",
          "course": "Conwy(Caernarvonshire)",
          "points": 28,
          "gross": 109,
          "net": 80,
          "chcp": 29
        },
        {
          "date": "2026-06-20",
          "course": "Conwy(Caernarvonshire)",
          "points": 17,
          "gross": 120,
          "net": 91,
          "chcp": 29
        },
        {
          "date": "2026-07-04",
          "course": "Conwy(Caernarvonshire)",
          "points": 15,
          "gross": 116,
          "net": 93,
          "chcp": 23
        }
      ]
    }
  ]
};
