/* AUTO-GENERATED by scrape.mjs on 2026-06-22 — do not hand-edit. */
window.CHOPPERS_DATA = {
  "competition": {
    "club": "Conwy Golf Club",
    "name": "Conwy Choppers",
    "subtitle": "Order of Merit",
    "format": "Best 6 Stableford",
    "startDate": "2026-05-30",
    "endDate": "2026-09-30",
    "lastUpdated": "2026-06-22",
    "bestN": 6,
    "recap": "<b>Tom</b> leads on 100. Tom's best week (+35).",
    "moverId": "tom",
    "celebrate": false
  },
  "players": [
    {
      "id": "tom",
      "name": "Tom Williams",
      "short": "Tom",
      "handicap": "+1.3",
      "handicapTrend": 0,
      "handicapHistory": [
        -1.3,
        -1.3,
        -1.2,
        -1.3,
        -1.3
      ],
      "movement": 0,
      "rounds": [
        {
          "date": "2026-06-21",
          "course": "Conwy(Caernarvonshire)",
          "points": 35,
          "gross": 74,
          "net": 73,
          "chcp": 1
        },
        {
          "date": "2026-05-30",
          "course": "Conwy(Caernarvonshire)",
          "points": 33,
          "gross": 76,
          "net": 75,
          "chcp": 1
        },
        {
          "date": "2026-06-20",
          "course": "Conwy(Caernarvonshire)",
          "points": 32,
          "gross": 77,
          "net": 76,
          "chcp": 1
        }
      ]
    },
    {
      "id": "josh",
      "name": "Josh Morris",
      "short": "Josh",
      "handicap": "2.7",
      "handicapTrend": null,
      "handicapHistory": [
        2.7
      ],
      "movement": 0,
      "rounds": [
        {
          "date": "2026-05-30",
          "course": "Conwy (Caernarvonshire)",
          "points": 30
        },
        {
          "date": "2026-06-20",
          "course": "Conwy (Caernarvonshire)",
          "points": 26,
          "gross": 88,
          "net": 82,
          "chcp": 6
        }
      ]
    },
    {
      "id": "callum",
      "name": "Callum Bennett",
      "short": "Callum",
      "handicap": "21.3",
      "handicapTrend": null,
      "handicapHistory": [
        21.3
      ],
      "movement": 0,
      "rounds": [
        {
          "date": "2026-06-05",
          "course": "Conwy (Caernarvonshire)",
          "points": 36
        },
        {
          "date": "2026-06-20",
          "course": "Conwy (Caernarvonshire)",
          "points": 17,
          "gross": 120,
          "net": 91,
          "chcp": 29
        }
      ]
    }
  ]
};
