/* AUTO-GENERATED by scrape.mjs on 2026-07-16 — do not hand-edit. */
window.CHOPPERS_DATA = {
  "competition": {
    "club": "Conwy Golf Club",
    "name": "Conwy Choppers",
    "subtitle": "Order of Merit",
    "format": "Best 6 Stableford",
    "startDate": "2026-05-30",
    "endDate": "2026-09-30",
    "lastUpdated": "2026-07-16",
    "bestN": 6,
    "recap": "<b>Tom</b> leads on 200.",
    "moverId": null,
    "celebrate": false
  },
  "players": [
    {
      "id": "tom",
      "name": "Tom Williams",
      "short": "Tom",
      "handicap": "+1.6",
      "handicapTrend": -0.3,
      "handicapHistory": [
        -1.3,
        -1.5,
        -1.6,
        -1.6,
        -1.6,
        -1.6
      ],
      "movement": 0,
      "rounds": [
        {
          "date": "2026-06-21",
          "course": "Conwy(Caernarvonshire)",
          "points": 35,
          "gross": 74,
          "net": 73,
          "chcp": 1
        },
        {
          "date": "2026-07-09",
          "course": "Wallasey",
          "points": 34,
          "gross": 73,
          "net": 74,
          "chcp": -1
        },
        {
          "date": "2026-07-01",
          "course": "Bromborough",
          "points": 34,
          "gross": 73,
          "net": 74,
          "chcp": -1
        },
        {
          "date": "2026-05-30",
          "course": "Conwy(Caernarvonshire)",
          "points": 33,
          "gross": 76,
          "net": 75,
          "chcp": 1
        },
        {
          "date": "2026-07-11",
          "course": "Conwy(Caernarvonshire)",
          "points": 32,
          "gross": 77,
          "net": 76,
          "chcp": 1
        },
        {
          "date": "2026-06-20",
          "course": "Conwy(Caernarvonshire)",
          "points": 32,
          "gross": 77,
          "net": 76,
          "chcp": 1
        },
        {
          "date": "2026-07-08",
          "course": "Conwy(Caernarvonshire)",
          "points": 28,
          "gross": 78,
          "net": 80,
          "chcp": -2
        }
      ]
    },
    {
      "id": "josh",
      "name": "Josh Morris",
      "short": "Josh",
      "handicap": "2.5",
      "handicapTrend": null,
      "handicapHistory": [
        2.5
      ],
      "movement": 0,
      "rounds": [
        {
          "date": "2026-07-09",
          "course": "Wallasey",
          "points": 36,
          "gross": 76,
          "net": 72,
          "chcp": 4
        },
        {
          "date": "2026-05-30",
          "course": "Conwy (Caernarvonshire)",
          "points": 30
        },
        {
          "date": "2026-07-04",
          "course": "Conwy (Caernarvonshire)",
          "points": 27,
          "gross": 84,
          "net": 81,
          "chcp": 3
        },
        {
          "date": "2026-06-20",
          "course": "Conwy (Caernarvonshire)",
          "points": 26,
          "gross": 88,
          "net": 82,
          "chcp": 6
        }
      ]
    },
    {
      "id": "callum",
      "name": "Callum Bennett",
      "short": "Callum",
      "handicap": "21.3",
      "handicapTrend": null,
      "handicapHistory": [
        21.3
      ],
      "movement": 0,
      "rounds": [
        {
          "date": "2026-06-05",
          "course": "Conwy (Caernarvonshire)",
          "points": 36
        },
        {
          "date": "2026-06-20",
          "course": "Conwy (Caernarvonshire)",
          "points": 17,
          "gross": 120,
          "net": 91,
          "chcp": 29
        },
        {
          "date": "2026-07-04",
          "course": "Conwy (Caernarvonshire)",
          "points": 15,
          "gross": 116,
          "net": 93,
          "chcp": 23
        }
      ]
    }
  ]
};
